version: '3.3'

services:
  mariadb:
    image: mariadb/server:10.3
    restart: always
    environment:
      - MARIADB_DATABASE=blog
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306


